# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('team_name', models.CharField(db_index=True, max_length=200)),
                ('access_token', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
