# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='user_id',
            field=models.CharField(default='dsad', max_length=200),
            preserve_default=False,
        ),
    ]
