# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usagelog_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagelog',
            old_name='slack_url',
            new_name='reddit_url',
        ),
    ]
